version: '2'
services:
  web:
    build: .
    # command: ["node", "web.js"]
    command: ["bin/web"]
    environment:
      - REDIS_URL
      - NODE_ENV=development
    labels:
      - convox.port.443.protocol=https
    links:
      - redis
    ports:
      - 80:8000
      - 443:8000
  worker:
    build: .
    # command: ["node", "worker.js"]
    command: ["bin/worker"]
    environment:
      - GITHUB_API_TOKEN
      - NODE_ENV=development
      - REDIS_URL
    links:
      - redis
  redis:
    image: convox/redis
    ports:
      - 6379

